services:
  # Backend API Service
  - type: web
    name: airport-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: airport-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist/frontend
    envVars:
      - key: API_URL
        value: https://airport-backend.onrender.com
